# Manipulación y Transformación de Datos
## Gabriel Daniel Aguilar Luna
### _Facultad de Ingeniería, Universidad Nacional Autónoma de México_
### _Ciudad de México, México_
#### gabriel.aguilar@ingenieria.unam.edu
***

In [2]:
import numpy as np
import pandas as pd

In [11]:
listaPython = [1, 2, 3, 4, 5, 6, 7, 8, 9]
listaNumpy = np.array (listaPython)
listaNumpy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
type(listaNumpy)

numpy.ndarray

In [19]:
matrizPy = [[11,12,13],[21,22,23],[31,32,33]]
matriz = np.array(matrizPy)
matriz

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [12]:
listaNumpy[0]

1

In [13]:
listaNumpy[0] + listaNumpy[5]

7

In [17]:
matriz[0]

array([11, 12, 13])

In [20]:
matrizPy[0,2]

TypeError: list indices must be integers or slices, not tuple

In [18]:
matriz[0,2]

13

In [22]:
listaNumpy[2:6]

array([3, 4, 5, 6])

In [23]:
listaNumpy[:6]

array([1, 2, 3, 4, 5, 6])

In [24]:
listaNumpy[2:]

array([3, 4, 5, 6, 7, 8, 9])

Podemos indicar un intervalo:

In [25]:
listaNumpy[::3]

array([1, 4, 7])